#' Model the book as Poisson events.
#' This demonstrates constructing a book from limit orders and trades
#' generated by a poisson process. 
#' @param num The number of iterations to model
#' @export
model.poisson <- function(num=100) {

	numobs <- num
	
	orders <<- data.table(id=1:1000000, sym=rep("sym",1000000), trader=rep("t",1000000), price=rep(0,1000000), side=rep(0,1000000), qty=rep(0,1000000), tradeype=rep("tt",1000000), key="id")
	
	# arrival rates
	askLimitTradeLambda <- 0.16
	bidLimitTradeLambda <- 0.16
	askMarketTradeLambda <- 0.08
	bidMarketTradeLambda <- 0.08
	ask0QuoteLambda <- 0.29
	bid0QuoteLambda <- 0.29
	ask1QuoteLambda <- 0.19
	bid1QuoteLambda <- 0.19
	ask2QuoteLambda <- 0.09
	bid2QuoteLambda <- 0.09


	# model arrivals
	askLimitTradeEvents <- abs(round(rpois(numobs, askLimitTradeLambda) * rnorm(numobs, 6)))
	bidLimitTradeEvents <- abs(round(rpois(numobs, bidLimitTradeLambda) * rnorm(numobs, 6)))
	askMarketTradeEvents <- abs(round(rpois(numobs, askMarketTradeLambda) * rnorm(numobs, 6)))
	bidMarketTradeEvents <- abs(round(rpois(numobs, bidMarketTradeLambda) * rnorm(numobs, 6)))
	ask0QuoteEvents <- abs(round(rpois(numobs, ask0QuoteLambda) * rnorm(numobs, 2)))
	bid0QuoteEvents <- abs(round(rpois(numobs, bid0QuoteLambda) * rnorm(numobs, 2))) 
	ask1QuoteEvents <- abs(rpois(numobs, ask1QuoteLambda))
	bid1QuoteEvents <- abs(rpois(numobs, bid1QuoteLambda))
	ask2QuoteEvents <- abs(rpois(numobs, ask2QuoteLambda))
	bid2QuoteEvents <- abs(rpois(numobs, bid2QuoteLambda))

	
	# init the book
	result <- .C("init", as.integer(num), as.integer(10000), as.integer(9999), PACKAGE='mobster')

	for (i in 1:numobs) {
	
		ob <- get.ob()
		
		bestAsk <- ob[10,]
		bestBid <- ob[11,]
	
		spread <- ob[10,]$price - ob[11,]$price  
		if(spread >0.01) {
			# randomly choose to fill bid or ask (assumes the market will supply liquidity at the best price)
			if(rnorm(1,0) > 0) {
				limit("sym", "poisson", 1, bestBid$price+0.01, ask0QuoteEvents[i], "GTC")
				limit("sym", "poisson", 1, bestBid$price+0.02, ask1QuoteEvents[i], "GTC")
				limit("sym", "poisson", 1, bestBid$price+0.03, ask2QuoteEvents[i], "GTC")
			} else {
				limit("sym", "poisson", 0, bestAsk$price-0.01, bid0QuoteEvents[i], "GTC")
				limit("sym", "poisson", 0, bestAsk$price-0.02, bid1QuoteEvents[i], "GTC")
				limit("sym", "poisson", 0, bestAsk$price-0.03, bid2QuoteEvents[i], "GTC")
			}
		} else {
			# normal quote arrival
			limit("sym", "poisson", 1, ob[10,]$price, ask0QuoteEvents[i], "GTC")
			limit("sym", "poisson", 0, ob[11,]$price, bid0QuoteEvents[i], "GTC")
			limit("sym", "poisson", 1, ob[9,]$price, ask1QuoteEvents[i], "GTC")
			limit("sym", "poisson", 0, ob[12,]$price, bid1QuoteEvents[i], "GTC")
			limit("sym", "poisson", 1, ob[8,]$price, ask2QuoteEvents[i], "GTC")
			limit("sym", "poisson", 0, ob[13,]$price, bid2QuoteEvents[i], "GTC")			
		}		
		
		# limit trade arrival
		limit("sym", "poisson", 1, ob[11,]$price, askLimitTradeEvents[i], "GTC")
		limit("sym", "poisson", 0, ob[10,]$price, bidLimitTradeEvents[i], "GTC")
	
		# market trade arrival
		if(askMarketTradeEvents[i]>0) {
			market("sym", "poisson", 1, 100.00, askMarketTradeEvents[i])
		}
		if(bidMarketTradeEvents[i]>0) {
			market("sym", "poisson", 0, 100.00, bidMarketTradeEvents[i])
		}

		
	}
}

